### ISSUE TITLE
License??

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [lucasmsa/arkham-theme#1]
Hey, Lucas :)

I really like your theme (IT'S SUPERB, GREAT WORK :+1: :tada: :clap:), and would like to make a similar one for [my game engine](https://github.com/ct-js/ct-js).

What's the license of your theme? Do you allow derivatives??

**Comment by lucasmsa** [comment]
No problem in using it and creating derivatives, I've added MIT License to it just now. Thanks for the support!!! 😄

**Comment by CosmoMyzrailGorynych** [comment]
Yaaaay! Thanks for your hard work and for being generous :heart:
