### ISSUE TITLE
What is the font family used in the examples?

### ISSUE THREAD

**Issue by gabrielpacheco23** [lucasmsa/arkham-theme#4]

**Comment by danilodecanini** [comment]
I would like to know too

**Comment by saifahn** [comment]
@gabrielpacheco23 @danilodecanini 

Not sure if you're still looking, but I'm pretty sure it's [Dank Mono](https://medium.com/@philpl/what-sets-dank-mono-apart-1bbdc1cc3cbd)

It's a paid font you can get from [the creator's gumroad page here](https://philpl.gumroad.com/l/dank-mono).

CodeSandbox used to have it installed in their editor by default, but it seems like that's gone and I'm not sure if there are other places you can try it for free.
